### ISSUE TITLE
Проверка ДЗ, 2 неделя

### ISSUE THREAD

**Issue by xabuk44** [xabuk44/W2_homework_functions#1]
Хотел уточнить 
C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.3\helpers\pycharm\docrunner.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

выдает это при доктесте. нужно ли исправлять ее как - либо?

**Comment by coursar** [comment]
Не нужно

Исправить нужно #2 #3 #4 #5

**Comment by xabuk44** [comment]
Исправлено.
